# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Publishing date')),
                ('teaser', models.TextField()),
                ('text', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
