# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
