# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_post_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
