# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_post_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
